name: Aggiorna dati

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Ogni giorno alle 08:00 UTC

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev

      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools

      - name: Install dependencies
        run: |
          # Blocchiamo yfinance a 0.2.60 per evitare il 401
          pip install yfinance==0.2.60 ta pandas
          pip install requests beautifulsoup4 scikit-learn xgboost PyGithub numpy feedparser
          pip install spacy==3.0.6
          python -m spacy download en_core_web_sm

      - name: Run prediction script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/predict_PRO.py
