name: Acknowledge All Subscriptions (Ultimi 3 giorni)

on:
  workflow_dispatch:

jobs:
  acknowledge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install google-api-python-client google-auth google-auth-httplib2 python-dateutil pytz

      - name: Run Acknowledge Script
        env:
          PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: python ack_all.py

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: ack_report
          path: ack_report.csv
