name: Aggiorna dati

on:
  workflow_dispatch:  # Solo avvio manuale

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev

      - name: Upgrade pip, setuptools e wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Python dependencies (senza compilazione)
        run: |
          pip install --no-cache-dir --upgrade numpy

          pip install --no-cache-dir --upgrade yfinance==0.2.63 \
            requests urllib3 feedparser

          pip install --no-cache-dir --upgrade pandas ta \
            beautifulsoup4 scikit-learn xgboost PyGithub

          pip install --no-cache-dir --prefer-binary spacy==3.7.2
          python -m spacy download en_core_web_sm

          pip install --no-cache-dir --upgrade torch torchvision torchaudio \
            --index-url https://download.pytorch.org/whl/cpu

          pip install --no-cache-dir --upgrade transformers

      - name: Debug versions
        run: |
          python - <<'EOF'
          import yfinance, requests, urllib3, numpy, pandas, spacy, torch, transformers
          print("yfinance    =", yfinance.__version__)
          print("requests    =", requests.__version__)
          print("urllib3     =", urllib3.__version__)
          print("numpy       =", numpy.__version__)
          print("pandas      =", pandas.__version__)
          print("spacy       =", spacy.__version__)
          print("torch       =", torch.__version__)
          print("transformers=", transformers.__version__)
          EOF

      - name: Run prediction script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/predict_PRO.py
