name: Aggiorna dati
on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'    # ← qui abbiamo aggiornato

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install yfinance==0.2.58 ta pandas
          pip install requests beautifulsoup4 scikit-learn xgboost PyGithub numpy feedparser
          pip install spacy==3.0.6
          python -m spacy download en_core_web_sm

          # per il sentiment model
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install transformers

      - name: Run prediction script
        run: python scripts/predict_PRO.py
