name: Manual Financial Forecast

on:
  workflow_dispatch:  # abilita l'esecuzione manuale
    inputs:
      ticker:
        description: 'Ticker (es: AAPL, TSLA)'
        required: true
        default: 'AAPL'
      start_date:
        description: 'Data di inizio (es: 2020-01-01)'
        required: true
        default: '2020-01-01'
      end_date:
        description: 'Data di fine (opzionale)'
        required: false

jobs:
  forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas scikit-learn

    - name: Run quantum_new.py
      run: |
        python scripts/quantum_new.py \
          --ticker "${{ github.event.inputs.ticker }}" \
          --start-date "${{ github.event.inputs.start_date }}" \
          --end-date "${{ github.event.inputs.end_date }}"
