name: Python Financial Forecast

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  forecast:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install yfinance pandas scikit-learn; fi

    - name: Run forecasting script
      # se il tuo script si chiama diversamente, modifica predict.py
      run: |
        python scripts/quantum_new.py --ticker AAPL --start-date 2020-01-01

    - name: Upload results as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: forecast-output
        path: ./output.log
