name: QUANTUM Analysis

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        batch: [
          "AAPL,MSFT,GOOGL,AMZN,META,TSLA,V",
          "JPM,JNJ,WMT,NVDA,PYPL,DIS,NFLX",
          "NIO,NRG,ADBE,INTC,CSCO,PFE,KO",
          "PEP,MRK,ABT,XOM,CVX,T,MCD",
          "NKE,HD,IBM,CRM,BMY,ORCL,ACN",
          "LLY,QCOM,HON,COST,SBUX,CAT,LOW",
          "MS,GS,AXP,INTU,AMGN,GE,FIS",
          "CVS,DE,BDX,NOW,SCHW,LMT,ADP",
          "C,PLD,NSC,TMUS,ITW,FDX,PNC",
          "SO,APD,ADI,ICE,ZTS,TJX,CL",
          "MMC,EL,GM,CME,EW,AON,D",
          "PSA,AEP,TROW,LNTH,HE,BTDR,NAAS",
          "SCHL,TGT,SYK,BKNG,DUK,USB",
          "EURUSD=X,USDJPY=X,GBPUSD=X,AUDUSD=X,USDCAD=X,USDCHF=X,NZDUSD=X",
          "EURGBP=X,EURJPY=X,GBPJPY=X,AUDJPY=X,CADJPY=X,CHFJPY=X,EURAUD=X",
          "EURNZD=X,EURCAD=X,EURCHF=X,GBPCHF=X,AUDCAD=X,BTC-USD,ETH-USD",
          "LTC-USD,XRP-USD,BCH-USD,EOS-USD,XLM-USD,ADA-USD,TRX-USD",
          "NEO-USD,DASH-USD,XMR-USD,ETC-USD,ZEC-USD,BNB-USD,DOGE-USD",
          "USDT-USD,LINK-USD,ATOM-USD,XTZ-USD,CC=F,GC=F,SI=F",
          "CL=F"
        ]
      max-parallel: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests yfinance ta pennylane scikit-learn

      - name: Run quantum kernel analysis
        env:
          ASSETS: ${{ matrix.batch }}
        run: python scripts/quantum_main.py
